### ISSUE TITLE
feature: Config for turning off the animation

### ISSUE THREAD

**Issue by Xennis** [filiphric/slidev-theme-excali-slide#2]
Thanks for this nice theme! It would be great if the animation of the marker swipe could be turned off (for the headline of a slide). It can be distracting. Can you please add a config for this?

**Comment by filiphric** [comment]
released in 1.3.0 🎉  you can now set a new option: `marker-animation` to either `enabled` or `disabled` to toggle the animation. it’s on by default

**Comment by Xennis** [comment]
Thanks alot.
